repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.40.0
  hooks:
    - id: eslint
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
    - id: shellcheck
